CREATE TABLE IF NOT EXISTS ingredient_category (
  ic_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ic_name VARCHAR NOT NULL,
  ic_parent_id BIGINT
);

CREATE TABLE IF NOT EXISTS ingredient (
  i_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  i_name VARCHAR NOT NULL,
  i_type BIGINT REFERENCES ingredient_category NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ingredient_type ON ingredient (i_type);

CREATE TABLE IF NOT EXISTS recipe (
  r_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  r_name VARCHAR NOT NULL,
  r_duration_min INTEGER NOT NULL,
  r_duration_max INTEGER,
  r_orig_url VARCHAR,
  r_steps VARCHAR []
);

CREATE TABLE IF NOT EXISTS recipe_ingredient (
  ri_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ri_recipe_id BIGINT REFERENCES recipe NOT NULL,
  ri_order SMALLINT NOT NULL,
  ri_ingredient_id BIGINT NOT NULL REFERENCES ingredient,
  ri_quantity INTEGER,
  ri_modifier VARCHAR,
  ri_unit VARCHAR
);

CREATE INDEX IF NOT EXISTS idx_recipe_ingredient_recipe ON recipe_ingredient (ri_recipe_id);
